export { default as GithubIcon } from "@/assets/svg/github-svgrepo-com (2).svg"
export { default as ReactIcon } from "@/assets/svg/react-svgrepo-com.svg"
export { default as PostgresIcon } from "@/assets/svg/PostgresSQL.svg"
export { default as ExpressIcon } from "@/assets/svg/Express.svg"
export { default as NextJs } from "@/assets/svg/nextjs-svgrepo-com (1).svg"
export { default as Tailwind } from "@/assets/svg/tailwindcss-svgrepo-com.svg"
export { default as NodejsIcon } from "@/assets/svg/nodejs-svgrepo-com (1).svg"
export { default as Typescript } from "@/assets/svg/typescript-logo-svgrepo-com.svg"
export { default as HTML } from "@/assets/svg/html-5-svgrepo-com.svg"
export { default as gitIcon } from "@/assets/svg/git-svgrepo-com.svg"
export { default as PrismaIcon } from "@/assets/svg/prisma-svgrepo-com (1).svg"
export { default as PythonIcon } from "@/assets/svg/python-svgrepo-com.svg"
export { default as TailwindCss } from "@/assets/svg/tailwind-svgrepo-com.svg"

